"""adiciona campos de calculo a proposta

Revision ID: 47574691958b
Revises: 8784be49bfe0
Create Date: 2025-10-03 10:46:24.044159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47574691958b'
down_revision = '8784be49bfe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumption_input_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('avg_consumption_kwh', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_bill_brl', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('grid_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('solar_irradiance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_column('solar_irradiance')
        batch_op.drop_column('grid_type')
        batch_op.drop_column('avg_bill_brl')
        batch_op.drop_column('avg_consumption_kwh')
        batch_op.drop_column('consumption_input_type')

    # ### end Alembic commands ###
