"""adiciona concessionarias e taxas a proposta

Revision ID: 4786e9973c4a
Revises: 47574691958b
Create Date: 2025-10-03 11:27:51.947062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4786e9973c4a'
down_revision = '47574691958b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concessionaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fio_b_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concessionaria')),
    sa.UniqueConstraint('name', name=op.f('uq_concessionaria_name'))
    )
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kwh_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('public_lighting_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('concessionaria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_proposal_concessionaria_id_concessionaria'), 'concessionaria', ['concessionaria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_proposal_concessionaria_id_concessionaria'), type_='foreignkey')
        batch_op.drop_column('concessionaria_id')
        batch_op.drop_column('public_lighting_fee')
        batch_op.drop_column('kwh_price')

    op.drop_table('concessionaria')
    # ### end Alembic commands ###
