"""adiciona campos pf e pj ao cliente

Revision ID: 8784be49bfe0
Revises: e9794563e4a7
Create Date: 2025-10-03 09:48:29.453999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8784be49bfe0'
down_revision = 'e9794563e4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fantasy_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cpf_cnpj', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('state_registration', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('complement', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=True))
        batch_op.drop_index(batch_op.f('ix_client_email'))
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_cpf_cnpj'), ['cpf_cnpj'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_cpf_cnpj'))
        batch_op.drop_index(batch_op.f('ix_client_email'))
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=1)
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('complement')
        batch_op.drop_column('number')
        batch_op.drop_column('cep')
        batch_op.drop_column('state_registration')
        batch_op.drop_column('cpf_cnpj')
        batch_op.drop_column('fantasy_name')
        batch_op.drop_column('client_type')

    # ### end Alembic commands ###
