"""adiciona campos detalhados a proposta

Revision ID: e9794563e4a7
Revises: 
Create Date: 2025-10-02 21:44:21.007025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9794563e4a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_client_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client'))
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_timestamp'), ['timestamp'], unique=False)

    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('total_investment', sa.Float(), nullable=True),
    sa.Column('estimated_savings_per_year', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('system_power_kwp', sa.Float(), nullable=True),
    sa.Column('monthly_production_kwh', sa.JSON(), nullable=True),
    sa.Column('payback_years', sa.Float(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_proposal_client_id_client')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_proposal_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal'))
    )
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_status'), ['status'], unique=False)

    op.create_table('proposal_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], name=op.f('fk_proposal_item_proposal_id_proposal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_item'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal_item')
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_status'))
        batch_op.drop_index(batch_op.f('ix_proposal_creation_date'))

    op.drop_table('proposal')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_timestamp'))
        batch_op.drop_index(batch_op.f('ix_client_name'))
        batch_op.drop_index(batch_op.f('ix_client_email'))

    op.drop_table('client')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
